version: "3.7"

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    #      MYSQL_DATABASE: baseball-quiz
    ports:
      - "3306:3306"
  mysql-test:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-db
    ports:
      - "3307:3306"

volumes:
  mysql-data:
